# Generated by Django 5.0 on 2025-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_assets', models.JSONField(default=list)),
                ('investor_type', models.CharField(max_length=100)),
                ('content_preferences', models.JSONField(default=list)),
            ],
        ),
    ]
