import { useState, useEffect } from 'react';
import Card from '../components/Card';
import client from '../api/client';

function Dashboard() {
  const [news, setNews] = useState([]);
  const [prices, setPrices] = useState({});
  const [aiInsight, setAiInsight] = useState('');
  const [aiSource, setAiSource] = useState(null); // Track if insight is from AI or fallback
  const [memeUrl, setMemeUrl] = useState('');
  const [loading, setLoading] = useState(true);

  const fetchAllData = async () => {
    try {
      const [newsRes, pricesRes] = await Promise.all([
        client.get('/dashboard/news/'),
        client.get('/dashboard/prices/'),
      ]);
      setNews(newsRes.data);
      setPrices(pricesRes.data);
    } catch (err) {
      console.error('Error fetching data:', err);
    }
  };

  const fetchAiAndMeme = async () => {
    try {
      const [aiRes, memeRes] = await Promise.all([
        client.get('/dashboard/ai-insight/'),
        client.get('/dashboard/meme/'),
      ]);
      setAiInsight(aiRes.data.insight);
      setAiSource(aiRes.data.source || 'fallback'); // Track source
      setMemeUrl(memeRes.data.url);
    } catch (err) {
      console.error('Error fetching AI/Meme:', err);
    }
  };

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      await fetchAllData();
      await fetchAiAndMeme();
      setLoading(false);
    };
    loadData();
  }, []);

  const handleRefresh = async () => {
    await fetchAiAndMeme();
  };

  const handleVote = async (section, vote) => {
    try {
      await client.post('/dashboard/vote/', { section, vote });
    } catch (err) {
      console.error('Error voting:', err);
    }
  };

  if (loading) {
    return <div className="dashboard-container">Loading...</div>;
  }

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>Dashboard</h1>
        <button onClick={handleRefresh} className="refresh-btn">
          Refresh Content
        </button>
      </div>
      <div className="dashboard-grid">
        <Card
          title="Market News"
          content={
            <div className="news-list">
              {news.length > 0 ? (
                news.map((item, idx) => (
                  <div key={idx} className="news-item">
                    <h4>{item.title}</h4>
                    <p className="news-source">{item.source}</p>
                    <a href={item.url} target="_blank" rel="noopener noreferrer">
                      Read more
                    </a>
                  </div>
                ))
              ) : (
                <p>Loading news...</p>
              )}
            </div>
          }
          onUpvote={() => handleVote('news', 1)}
          onDownvote={() => handleVote('news', -1)}
        />
        <Card
          title="Coin Prices"
          content={
            <div className="prices-list">
              {Object.keys(prices).length > 0 ? (
                Object.entries(prices).map(([asset, price]) => (
                  <div key={asset} className="price-item">
                    <strong>{asset}:</strong> ${typeof price === 'number' ? price.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : 'N/A'}
                  </div>
                ))
              ) : (
                <p>Loading prices...</p>
              )}
            </div>
          }
          onUpvote={() => handleVote('prices', 1)}
          onDownvote={() => handleVote('prices', -1)}
        />
        <Card
          title="AI Insight of the Day"
          content={
            <div>
              <p className="ai-insight">{aiInsight || 'Loading insight...'}</p>
              {aiSource && (
                <p style={{ fontSize: '12px', color: '#999', marginTop: '8px', fontStyle: 'italic' }}>
                  {aiSource === 'ai' ? '✨ Generated by AI' : '📝 Personalized insight'}
                </p>
              )}
            </div>
          }
          onUpvote={() => handleVote('ai', 1)}
          onDownvote={() => handleVote('ai', -1)}
        />
        <Card
          title="Fun Crypto Meme"
          content={
            <div className="meme-container">
              {memeUrl ? (
                <img 
                  src={memeUrl} 
                  alt="Crypto Meme" 
                  className="meme-image" 
                  onError={(e) => {
                    // Hide image on error instead of trying another URL
                    e.target.style.display = 'none';
                    const parent = e.target.parentElement;
                    if (parent && !parent.querySelector('.meme-error')) {
                      const errorMsg = document.createElement('p');
                      errorMsg.className = 'meme-error';
                      errorMsg.textContent = 'Meme unavailable';
                      errorMsg.style.color = '#999';
                      parent.appendChild(errorMsg);
                    }
                  }} 
                />
              ) : (
                <p>Loading meme...</p>
              )}
            </div>
          }
          onUpvote={() => handleVote('meme', 1)}
          onDownvote={() => handleVote('meme', -1)}
        />
      </div>
    </div>
  );
}

export default Dashboard;

